export type Role = 'ADMIN' | 'VERIFIER' | 'AGENT' | 'LANDLORD' | 'USER' | 'MODERATOR' | 'COMPANY_ADMIN' | 'COMPANY_AGENT' | 'INDEPENDENT_AGENT' | 'SELLER' | 'TENANT' | 'BUYER' | 'ADVERTISER';
export const ROLES: Role[] = ['ADMIN', 'VERIFIER', 'AGENT', 'LANDLORD', 'USER', 'MODERATOR', 'COMPANY_ADMIN', 'COMPANY_AGENT', 'INDEPENDENT_AGENT', 'SELLER', 'TENANT', 'BUYER', 'ADVERTISER'];
