import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';

export const env = createEnv({
  server: {
    PORT: z.coerce.number().default(3001),
    WEB_ORIGIN: z.string().optional(),
    DATABASE_URL: z.string().url(),
    REDIS_URL: z.string().url(),
    JWT_SECRET: z.string().min(32),
    NEXTAUTH_SECRET: z.string().min(32),
    EMAIL_SERVER: z.string(),
    EMAIL_FROM: z.string().email(),
    GOOGLE_CLIENT_ID: z.string(),
    GOOGLE_CLIENT_SECRET: z.string(),
    S3_ACCESS_KEY: z.string(),
    S3_SECRET_KEY: z.string(),
    S3_ENDPOINT: z.string().url(),
    S3_BUCKET: z.string().min(1),
    FACEBOOK_PAGE_ID: z.string().optional(),
    FACEBOOK_ACCESS_TOKEN: z.string().optional(),
    WHATSAPP_PHONE_NUMBER_ID: z.string().optional(),
    WHATSAPP_ACCESS_TOKEN: z.string().optional(),
    ADSERVER_ENABLED: z.coerce.boolean().default(false),
    ADSERVER_REWARD_SHARE: z.coerce.number().min(0).max(1).default(0.2),
    VAT_PERCENT: z.coerce.number().min(0).max(100).default(15),
    PAYNOW_INTEGRATION_ID: z.string().optional(),
    PAYNOW_INTEGRATION_KEY: z.string().optional(),
    PAYNOW_RESULT_URL: z.string().url().optional(),
    PAYNOW_RETURN_URL: z.string().url().optional(),
    PAYMENT_METHOD_BLOCKLIST: z.string().optional(),
    MAP_TILES_URL: z.string().min(1).default('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'),
    WS_PROVIDER: z.enum(['INTERNAL', 'PUSHER']).default('INTERNAL'),
    PUSHER_KEY: z.string().optional(),
    PUSHER_CLUSTER: z.string().optional(),
    WALLET_MIN_PAYOUT_CENTS: z.coerce.number().min(0).default(2000),
    WALLET_EARNINGS_COOL_OFF_DAYS: z.coerce.number().min(0).max(30).default(5),
    WALLET_MAX_PAYOUTS_PER_DAY: z.coerce.number().min(1).max(10).default(2)
  },
  client: {
    NEXT_PUBLIC_API_BASE_URL: z.string().url(),
    NEXT_PUBLIC_ADSENSE_CLIENT_ID: z.string().optional(),
    NEXT_PUBLIC_ADSENSE_FEED_SLOT: z.string().optional(),
    NEXT_PUBLIC_ADSENSE_LISTING_SLOT: z.string().optional()
  },
  runtimeEnv: {
    PORT: process.env.PORT,
    WEB_ORIGIN: process.env.WEB_ORIGIN,
    DATABASE_URL: process.env.DATABASE_URL,
    REDIS_URL: process.env.REDIS_URL,
    JWT_SECRET: process.env.JWT_SECRET,
    NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
    EMAIL_SERVER: process.env.EMAIL_SERVER,
    EMAIL_FROM: process.env.EMAIL_FROM,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    S3_ACCESS_KEY: process.env.S3_ACCESS_KEY,
    S3_SECRET_KEY: process.env.S3_SECRET_KEY,
    S3_ENDPOINT: process.env.S3_ENDPOINT,
    S3_BUCKET: process.env.S3_BUCKET,
    FACEBOOK_PAGE_ID: process.env.FACEBOOK_PAGE_ID,
    FACEBOOK_ACCESS_TOKEN: process.env.FACEBOOK_ACCESS_TOKEN,
    WHATSAPP_PHONE_NUMBER_ID: process.env.WHATSAPP_PHONE_NUMBER_ID,
    WHATSAPP_ACCESS_TOKEN: process.env.WHATSAPP_ACCESS_TOKEN,
    ADSERVER_ENABLED: process.env.ADSERVER_ENABLED,
    ADSERVER_REWARD_SHARE: process.env.ADSERVER_REWARD_SHARE,
    VAT_PERCENT: process.env.VAT_PERCENT,
    PAYNOW_INTEGRATION_ID: process.env.PAYNOW_INTEGRATION_ID,
    PAYNOW_INTEGRATION_KEY: process.env.PAYNOW_INTEGRATION_KEY,
    PAYNOW_RESULT_URL: process.env.PAYNOW_RESULT_URL,
    PAYNOW_RETURN_URL: process.env.PAYNOW_RETURN_URL,
    PAYMENT_METHOD_BLOCKLIST: process.env.PAYMENT_METHOD_BLOCKLIST,
    MAP_TILES_URL: process.env.MAP_TILES_URL,
    WS_PROVIDER: process.env.WS_PROVIDER,
    PUSHER_KEY: process.env.PUSHER_KEY,
    PUSHER_CLUSTER: process.env.PUSHER_CLUSTER,
    WALLET_MIN_PAYOUT_CENTS: process.env.WALLET_MIN_PAYOUT_CENTS,
    WALLET_EARNINGS_COOL_OFF_DAYS: process.env.WALLET_EARNINGS_COOL_OFF_DAYS,
    WALLET_MAX_PAYOUTS_PER_DAY: process.env.WALLET_MAX_PAYOUTS_PER_DAY,
    NEXT_PUBLIC_API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
    NEXT_PUBLIC_ADSENSE_CLIENT_ID: process.env.NEXT_PUBLIC_ADSENSE_CLIENT_ID,
    NEXT_PUBLIC_ADSENSE_FEED_SLOT: process.env.NEXT_PUBLIC_ADSENSE_FEED_SLOT,
    NEXT_PUBLIC_ADSENSE_LISTING_SLOT: process.env.NEXT_PUBLIC_ADSENSE_LISTING_SLOT
  }
});
