ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "dateOfBirth" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "idNumber" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "addressLine1" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "addressCity" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "addressProvince" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "addressCountry" TEXT;
