-- AlterTable
ALTER TABLE "User" ADD COLUMN "trustScore" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "verificationScore" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "riskScore" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "profilePhoto" TEXT;
ALTER TABLE "User" ADD COLUMN "bio" TEXT;
ALTER TABLE "User" ADD COLUMN "location" TEXT;
